fragment PageParts on Page {
  blocks {
    __typename
    ... on PageBlocksHero {
      heading
      subheading
      description
      image
    }
    ... on PageBlocksProjects {
      heading
      subheading
      items {
        __typename
        image
        name
        description
        href
      }
    }
    ... on PageBlocksFeatures {
      items {
        __typename
        image
        title
        author
        category
        description
        href
      }
    }
  }
}

fragment PostParts on Post {
  title
  date
  image
  author
  category
  tags
  description
  body
}
